/**
 * Re-export shim — keeps existing `'../domain/stats'` imports working.
 * Real implementation lives in `./stats/` sub-modules.
 */
export {
  type DayTotals,
  type DeepDiveStats,
  type ExerciseSpend,
  type HabitStats,
  type IntervalModeSession,
  type SessionDetail,
  type StatsSnapshot,
  type TodayStats,
  type TrendsStats,
  type WeekTotal,
  WEEKDAY_LABELS,
  buildDailyTotals,
  calculateAdherencePercent,
  computeAverageMinutesPerDay,
  computeAverageSessionMinutes,
  computeBestDayThisWeek,
  computeCurrentStreak,
  computeCurrentWeekStreak,
  computeExerciseSessionStreak,
  computeIntervalModeAverageBpmIncrease,
  computeIntervalModeAverageIntervalDurationSeconds,
  computeIntervalModeIntervalsCompletedForDate,
  computeIntervalModeIntervalsCompletedForWeek,
  computeIntervalModeLongestStreak,
  computeIntervalModeTimedAdherence,
  computeLongestSessionMinutes,
  computeLongestStreak,
  computeMostConsistentWeekday,
  computeMostImprovedExerciseThisWeek,
  computeMostPracticedExercise,
  computeMostPracticedPlan,
  computeSessionsThisWeek,
  computeTopPracticedPlanThisWeek,
  computeWeekdayTotals,
  computeWeekOverWeekChangePercent,
  computeWeeklyTotals,
  countExercisesCompleted,
  countPracticeDays,
  countUniqueTabsPracticed,
  getDateRangeDays,
  getSessionLocalDate,
  getWeekStart,
  normalizeDisplayMinutes,
  selectMostPracticedExercise,
  toLocalDateKey,
} from './stats/index';
